name: Run nRF Cloud Location Service API tests

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  API_HOST: ${{ secrets.API_HOST }}
  TEAM_ID: ${{ secrets.TEAM_ID }}
  AGPS_SERVICE_KEY: ${{ secrets.AGPS_SERVICE_KEY }}
  PGPS_SERVICE_KEY: ${{ secrets.PGPS_SERVICE_KEY }}
  CELLGEO_SERVICE_KEY: ${{ secrets.CELLGEO_SERVICE_KEY }}
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run api:tests
