name: Run tests

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      api_host:
        description: 'API host'     
        required: true
        default: 'https://api.nrfcloud.com'

env:
  API_KEY: ${{ secrets.API_KEY }}
  API_HOST: ${{ github.event.inputs.api_host }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test